# Turn on validation, so we can use import:
version: ~> 1.0

jdk:
- openjdk8
import: land-of-apps/land-of-apps:travis/java-imports.yml
  
script:
- mvn -DargLine="-javaagent:appmap.jar -Dappmap.debug -Dappmap.config.file=./appmap.yml -Dappmap.output.directory=./tmp/appmap" test
- ./appmap_web.sh ./tmp/appmap
